--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -56,4 +56,4 @@
               if: failure()
               with:
                   name: test-snapshots-${{ matrix.julia-version }}-${{ matrix.os }}
-                  path: ${{ github.workspace }}/test/snapshots/*.html
+                  path: ${{ github.workspace }}/test/snapshots/*.html